### ISSUE TITLE
Hello, I need Veve Api

### ISSUE THREAD

**Issue by erkangcmn** [alienbuild/ecomiwiki_frontend#9]
Hello, i am developing application. I need Veve api. I have your api information.

Can I use your API information and some code?

**Comment by alienbuild** [comment]
Hey 👋

Thanks for reaching out. Unfortunately our api eith veve is exclusive for the time being and we are also under instructions not to serve out any data to third party developers using our own api. However if you're a js developer and want to help build the wiki you're more than welcome to contribute to this project.
